# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'summary.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(670, 10, 121, 20))
        self.username.setText("")
        self.username.setObjectName("username")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 181, 711))
        self.listWidget.setObjectName("listWidget")
        self.Race_label = QtWidgets.QLabel(self.centralwidget)
        self.Race_label.setGeometry(QtCore.QRect(20, 230, 161, 16))
        self.Race_label.setMinimumSize(QtCore.QSize(161, 0))
        self.Race_label.setObjectName("Race_label")
        self.Race_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Race_comboBox.setGeometry(QtCore.QRect(20, 250, 161, 26))
        self.Race_comboBox.setObjectName("Race_comboBox")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Race_comboBox.addItem("")
        self.Gender_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Gender_comboBox.setGeometry(QtCore.QRect(20, 300, 161, 26))
        self.Gender_comboBox.setObjectName("Gender_comboBox")
        self.Gender_comboBox.addItem("")
        self.Gender_comboBox.addItem("")
        self.Gender_comboBox.addItem("")
        self.Gender_label = QtWidgets.QLabel(self.centralwidget)
        self.Gender_label.setGeometry(QtCore.QRect(20, 280, 161, 16))
        self.Gender_label.setObjectName("Gender_label")
        self.edu_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.edu_comboBox.setGeometry(QtCore.QRect(20, 350, 161, 26))
        self.edu_comboBox.setObjectName("edu_comboBox")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.edu_comboBox.addItem("")
        self.Edu_label = QtWidgets.QLabel(self.centralwidget)
        self.Edu_label.setGeometry(QtCore.QRect(20, 330, 161, 16))
        self.Edu_label.setObjectName("Edu_label")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 460, 161, 26))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 440, 161, 16))
        self.label_4.setObjectName("label_4")
        self.Age_label = QtWidgets.QLabel(self.centralwidget)
        self.Age_label.setGeometry(QtCore.QRect(20, 380, 161, 16))
        self.Age_label.setObjectName("Age_label")
        self.Age_input = QtWidgets.QTextEdit(self.centralwidget)
        self.Age_input.setGeometry(QtCore.QRect(20, 400, 151, 31))
        self.Age_input.setObjectName("Age_input")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 500, 151, 32))
        self.pushButton.setObjectName("pushButton")
        self.Summary_table = QtWidgets.QTableView(self.centralwidget)
        self.Summary_table.setGeometry(QtCore.QRect(200, 360, 751, 361))
        self.Summary_table.setObjectName("Summary_table")
        self.Summary_table.horizontalHeader().setHighlightSections(False)
        self.Graph_label = QtWidgets.QLabel(self.centralwidget)
        self.Graph_label.setGeometry(QtCore.QRect(200, 10, 751, 341))
        self.Graph_label.setStyleSheet("#Graph_label {\n"
"    border: 3px solid gray;\n"
" }")
        self.Graph_label.setText("")
        self.Graph_label.setObjectName("Graph_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Race_label.setText(_translate("MainWindow", "Race"))
        self.Race_comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.Race_comboBox.setItemText(1, _translate("MainWindow", "Native American or Alaska Native"))
        self.Race_comboBox.setItemText(2, _translate("MainWindow", "Asian or Pacific Islander"))
        self.Race_comboBox.setItemText(3, _translate("MainWindow", "Black or African American "))
        self.Race_comboBox.setItemText(4, _translate("MainWindow", "White or European American"))
        self.Race_comboBox.setItemText(5, _translate("MainWindow", "Non-White Hispanic"))
        self.Race_comboBox.setItemText(6, _translate("MainWindow", "Bi- / multi-racial"))
        self.Race_comboBox.setItemText(7, _translate("MainWindow", "Other "))
        self.Gender_comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.Gender_comboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.Gender_comboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.Gender_label.setText(_translate("MainWindow", "Gender"))
        self.edu_comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.edu_comboBox.setItemText(1, _translate("MainWindow", "Less than High School "))
        self.edu_comboBox.setItemText(2, _translate("MainWindow", "High-School / GED"))
        self.edu_comboBox.setItemText(3, _translate("MainWindow", "Some College but no degree"))
        self.edu_comboBox.setItemText(4, _translate("MainWindow", "Diploma or certificate from vocational, technical or trade school"))
        self.edu_comboBox.setItemText(5, _translate("MainWindow", "Associates Degree"))
        self.edu_comboBox.setItemText(6, _translate("MainWindow", "Bachelors Degree"))
        self.edu_comboBox.setItemText(7, _translate("MainWindow", "Masters Degree"))
        self.edu_comboBox.setItemText(8, _translate("MainWindow", "Professional School Degree"))
        self.edu_comboBox.setItemText(9, _translate("MainWindow", "Doctorate"))
        self.Edu_label.setText(_translate("MainWindow", "Education Level"))
        self.label_4.setText(_translate("MainWindow", "Case Number"))
        self.Age_label.setText(_translate("MainWindow", "Age(25 or 25-42)"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

